[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ad_agents"
version = "0.1.0"
authors = [
  { name="AD Team" }
]
description = "AD Agents Platform"